### ISSUE TITLE
telnet is no output

### ISSUE THREAD

**Issue by dengrobert** [lefred/mysql_gr_routing_check#4]
when i  execute the mysql_gr_routing_check.sh , it can output; but when i telnet, is not thing ,please help.

![image](https://user-images.githubusercontent.com/72972982/96248517-42096380-0fde-11eb-9c1d-eabd67b4f251.png)

**Comment by lefred** [comment]
What info do you have in the error log related to xinetd ?

**Comment by dengrobert** [comment]
i have fix it  by add "source  /etc/profile" in    "mysql_gr_routing_check.sh"
tks for your answer.
